name: Pull Request
description: Contribute an improvement - new, improved form!
labels:
body:
  - type: markdown
    attributes:
      value: |
        Provide a general summary of your changes in the Title above.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your changes in detail.
    validations:
      required: true

  - type: textarea
    id: motivation-and-context
    attributes:
      label: Motivation and Context
      description: |
        Why is this change required? What problem does it solve?
        If it fixes any open issue, please link to the issue here.
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: How has this been tested?
      description: |
        Please describe in detail how you tested your changes.
        Include details of your testing environment, tests ran to see how your change affects other areas of the code, etc.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if appropriate)
      description: |
        Paste in any useful screenshots, with descriptions.
    validations:
      required: true

  - type: checkboxes
    id: types-of-changes
    attributes:
      label: Types of changes
      description: What types of changes does your code introduce? Select all that apply.
      options:
        - label: Bug fix (non-breaking change which fixes an issue)
        - label: Refactor (non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
        - label: New feature (non-breaking change which adds functionality)
        - label: Breaking change (fix or feature that would cause existing functionality to not work as expected)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Go over all the following points, and select all that apply.
        If you're unsure about any of these, don't hesitate to ask. We're here to help!
      options:
        - label: My code follows the code style of this project and passes `yarn run lint`.
        - label: My change requires a change to the documentation.
        - label: I have updated the documentation accordingly.
        - label: My change has adequate Unit Test coverage.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submiting this pull request, you agree to follow our [contributing guide](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: My contribution follow this project's [contributing guide](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CONTRIBUTING.md)
          required: true
        - label: I agree to follow this project's [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md)
          required: true
