name: Bug Report
description: File a bug report
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you start
        Please **make sure you are on the latest version of Tasks.**
        If you encountered the issue after you installed, updated, or reloaded the Tasks plugin, **please try restarting obsidian before reporting the bug**.
        Also, please make sure you **read and understand the [guide for good bug reports](https://publish.obsidian.md/tasks/Support+and+Help/Report+a+Bug)**.

  - type: checkboxes
    id: no-invalid-issues
    attributes:
      label: "⚠️ Check issue is valid."
      description: "This repository is not about the Obsidian app!"
      options:
        - label: "My request is about the [Tasks plugin for Obsidian](https://publish.obsidian.md/tasks/Introduction)."
          required: true

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "⚠️ Check that this issue hasn't been reported before. We know that Tasks has been broken by iOS and iPadOS 18.6 and 26 Public Beta 2."
      description: |
        **Known Issue**: We already know **iOS and iPadOS** versions **18.6** and **26 Public Beta 2** have completely broken the Tasks plugin's ability to read task lines with more than one emoji.
        This breaks many thinks, including:
        * Recurrence
        * Searches
        * Sorting
        * Grouping

        See [#3546](https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3546) and [#3546](https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3560).

        The **Label filters** may help make your search more focussed.
      options:
        - label: "I searched previous [Tasks plugin Bug Reports](https://github.com/obsidian-tasks-group/obsidian-tasks/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22+sort%3Acomments-desc) didn't find any similar reports."
          required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Which exact steps can a developer take to reproduce the issue?
        The more detail you provide, the easier it will be to narrow down and fix the bug.
        Please paste in tasks and/or queries **as text, not screenshots**.
        See [Give us text to copy](https://publish.obsidian.md/tasks/Support+and+Help/Report+a+Bug#Give+us+text+to+copy) for how to format your pasted text, and
        **why we cannot accept bug reports that require anyone to re-type text from screenshots or descriptive text**.
      placeholder: |
        Example of the level of detail needed to reproduce any bugs efficiently and reliably.
        1. Launch Obsidian Sandbox via the `Open Sandbox Vault` command.
        2. Install the Tasks plugin.
        3. Change the global filter to...
        4. Create a new note called `Demo problem`.
        5. Paste in a task with the text `- [x] Some special problem text`.
        6. Switch to Reading mode.
        7. etc
        (Mac users: a Safari bug strips newlines from this text.)
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Tell us what **should** happen, when **exactly** following the steps above.
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Current behaviour
      description: |
        Tell us what happens instead of the expected behavior.
        Adding of screenshots really helps.
    validations:
      required: true

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which Operating Systems are you using?
      description: You may select more than one.
      options:
        - label: Android
        - label: iPhone/iPad
        - label: Linux
        - label: macOS
        - label: Windows
    validations:
      required: true

  - type: input
    id: os-versions
    attributes:
      label: Operating System Version(s)
      description: Which operating system version(s) are you using?
    validations:
      required: true

  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian Version
      description: Which Obsidian version are you using?
      placeholder: 1.6.7
    validations:
      required: true

  - type: input
    id: tasks-version
    attributes:
      label: Tasks Plugin Version
      description: Which Tasks version are you using? (We only support Tasks version 7.0.0 and above)
      placeholder: 7.0.0
    validations:
      required: true

  - type: checkboxes
    id: other-plugins-disabled
    attributes:
      label: Checks
      description: Please confirm
      options:
        - label: I have tried it with all other plugins disabled and the error still occurs
          required: false

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: |
        Not obligatory, but please suggest a fix or reason for the bug, if you have an idea.
