blank_issues_enabled: false
contact_links:
  - name: Suggest a new feature
    url: https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/new?category=ideas
    about: Request a new feature or improvement in the Tasks plugin. Please search existing Discussion Ideas first, and up-vote, to avoid duplicates.
  - name: Ask a question
    url: https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/new?category=q-a
    about: Ask for help with using the Tasks plugin. In case your question has been asked before, for quicker results you can search existing Discussion Q&As.
