/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');

class RevealActiveFileButtonPlugin extends obsidian.Plugin {
    onload() {
        // Initialize
        this.app.workspace.onLayoutReady(() => {
            const explorers = this.getFileExplorers();
            explorers.forEach((exp) => {
                this.addRevealButton(exp);
            });
        });
        // File explorers that get opened later on
        this.registerEvent(this.app.workspace.on('layout-change', () => {
            const explorers = this.getFileExplorers();
            explorers.forEach((exp) => {
                this.addRevealButton(exp);
            });
        }));
    }
    onunload() {
        // Remove all reveal buttons
        const explorers = this.getFileExplorers();
        explorers.forEach((exp) => {
            this.removeRevealButton(exp);
        });
    }
    /**
     * Adds the reveal button to a file explorer leaf.
     * Returns the newly created button element or the old one if already there.
     */
    addRevealButton(explorer) {
        const container = explorer.view.containerEl;
        const navContainer = container.querySelector('div.nav-buttons-container');
        if (!navContainer) {
            return null;
        }
        const existingButton = this.getRevealButton(explorer);
        if (existingButton) {
            return;
        }
        const newIcon = createDiv();
        this.setButtonProperties(newIcon);
        newIcon.className = 'clickable-icon nav-action-button reveal-active-file-button';
        this.registerDomEvent(newIcon, 'click', () => {
            this.onButtonClick(explorer);
        });
        navContainer.appendChild(newIcon);
    }
    /**
     * Remove the reveal button from a given file explorer leaf.
     */
    removeRevealButton(explorer) {
        const button = this.getRevealButton(explorer);
        if (button) {
            button.remove();
        }
    }
    /**
     * Reveal the active file in the given file explorer
     */
    onButtonClick(explorer) {
        if (explorer) {
            this.revealActiveFile();
            // Send the command twice like a double-click, to handle the frequent case where Obsidian fails to jump to the file
            window.setTimeout(() => {
                this.revealActiveFile();
            }, 50);
        }
    }
    revealActiveFile() {
        this.app
            .commands.executeCommandById('file-explorer:reveal-active-file');
    }
    setButtonProperties(button) {
        obsidian.setIcon(button, 'crosshair');
        button.setAttribute('aria-label', 'Reveal active file');
    }
    /**
     * Returns all loaded file explorer leaves
     */
    getFileExplorers() {
        return this.app.workspace.getLeavesOfType('file-explorer');
    }
    /**
     * Get the reveal button for a given file explorer, if it exists
     */
    getRevealButton(explorer) {
        return explorer.view.containerEl.querySelector('.reveal-active-file-button');
    }
}

module.exports = RevealActiveFileButtonPlugin;


/* nosourcemap */