name: Verify Commit
on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install modules
        run: yarn

      - name: Run build
        run: yarn run build

      - name: Run TypeScript compiler ESLint
        run: yarn run lint

      - name: Run Markdown Lint
        run: yarn run lint:markdown

      - name: Run Jest
        run: yarn run test

      - name: Archive verified build
        uses: actions/upload-artifact@v3
        with:
          name: dist-verified
          path: |
            main.js
            manifest.json
            styles.css

      - name: Copy new build to Tasks-Demo vault
        run: ./scripts/Test-TasksInLocalObsidian.sh

      - name: Archive Tasks-Demo vault
        uses: actions/upload-artifact@v3
        with:
          name: Tasks-Demo-VerifyCommit-Build${{ github.run_number }}-Run${{ github.run_attempt }}
          path: |
            resources/sample_vaults/Tasks-Demo
